// Sample data for the trust system
// In a real implementation, this would be generated by your calculation system

const trustData = {
    // Last update timestamp
    lastUpdated: "May 10, 2025",
    
    // User data with trust scores and relationships
    users: [
        {
            username: "tech_guru",
            trustScore: 0.0923,
            trustors: 12,
            trustees: 8,
            interests: ["tech", "AI", "programming"],
            communityId: 1
        },
        {
            username: "science_fan",
            trustScore: 0.0812,
            trustors: 10,
            trustees: 6,
            interests: ["science", "space", "physics"],
            communityId: 1
        },
        {
            username: "ai_researcher",
            trustScore: 0.0762,
            trustors: 8,
            trustees: 5,
            interests: ["AI", "machine learning", "tech"],
            communityId: 1
        },
        {
            username: "code_master",
            trustScore: 0.0701,
            trustors: 7,
            trustees: 9,
            interests: ["programming", "open source", "tech"],
            communityId: 1
        },
        {
            username: "data_analyst",
            trustScore: 0.0656,
            trustors: 6,
            trustees: 4,
            interests: ["data science", "statistics", "programming"],
            communityId: 1
        },
        {
            username: "ufo_believer",
            trustScore: 0.0612,
            trustors: 9,
            trustees: 7,
            interests: ["UFOs", "aliens", "conspiracy"],
            communityId: 2
        },
        {
            username: "conspiracy_buff",
            trustScore: 0.0594,
            trustors: 8,
            trustees: 5,
            interests: ["conspiracy", "government", "UFOs"],
            communityId: 2
        },
        {
            username: "alien_hunter",
            trustScore: 0.0543,
            trustors: 7,
            trustees: 6,
            interests: ["aliens", "UFOs", "space"],
            communityId: 2
        },
        {
            username: "truth_seeker",
            trustScore: 0.0521,
            trustors: 6,
            trustees: 8,
            interests: ["conspiracy", "truth", "government"],
            communityId: 2
        },
        {
            username: "cosmic_explorer",
            trustScore: 0.0498,
            trustors: 5,
            trustees: 4,
            interests: ["space", "aliens", "UFOs"],
            communityId: 2
        },
        {
            username: "skeptic123",
            trustScore: 0.0476,
            trustors: 9,
            trustees: 7,
            interests: ["skepticism", "science", "debunking"],
            communityId: 3
        },
        {
            username: "fact_checker",
            trustScore: 0.0451,
            trustors: 8,
            trustees: 6,
            interests: ["facts", "debunking", "skepticism"],
            communityId: 3
        },
        {
            username: "rational_thinker",
            trustScore: 0.0423,
            trustors: 7,
            trustees: 5,
            interests: ["rationality", "science", "skepticism"],
            communityId: 3
        },
        {
            username: "evidence_first",
            trustScore: 0.0398,
            trustors: 6,
            trustees: 8,
            interests: ["evidence", "science", "skepticism"],
            communityId: 3
        },
        {
            username: "reality_check",
            trustScore: 0.0376,
            trustors: 5,
            trustees: 4,
            interests: ["debunking", "skepticism", "facts"],
            communityId: 3
        },
        {
            username: "news_junkie",
            trustScore: 0.0354,
            trustors: 7,
            trustees: 9,
            interests: ["news", "politics", "current events"],
            communityId: 4
        },
        {
            username: "political_analyst",
            trustScore: 0.0332,
            trustors: 6,
            trustees: 5,
            interests: ["politics", "analysis", "government"],
            communityId: 4
        },
        {
            username: "policy_wonk",
            trustScore: 0.0312,
            trustors: 5,
            trustees: 7,
            interests: ["policy", "politics", "government"],
            communityId: 4
        },
        {
            username: "current_events",
            trustScore: 0.0298,
            trustors: 4,
            trustees: 6,
            interests: ["news", "events", "world"],
            communityId: 4
        },
        {
            username: "legal_eagle",
            trustScore: 0.0276,
            trustors: 3,
            trustees: 5,
            interests: ["law", "politics", "justice"],
            communityId: 4
        }
    ],
    
    // Trust relationships (who trusts whom and how much)
    relationships: [
        // Tech community internal trust
        { source: "tech_guru", target: "science_fan", value: 200 },
        { source: "tech_guru", target: "ai_researcher", value: 300 },
        { source: "tech_guru", target: "code_master", value: 250 },
        { source: "science_fan", target: "tech_guru", value: 150 },
        { source: "science_fan", target: "data_analyst", value: 200 },
        { source: "ai_researcher", target: "tech_guru", value: 350 },
        { source: "ai_researcher", target: "data_analyst", value: 250 },
        { source: "code_master", target: "tech_guru", value: 200 },
        { source: "code_master", target: "ai_researcher", value: 150 },
        { source: "data_analyst", target: "ai_researcher", value: 300 },
        { source: "data_analyst", target: "code_master", value: 200 },
        
        // UFO community internal trust
        { source: "ufo_believer", target: "conspiracy_buff", value: 250 },
        { source: "ufo_believer", target: "alien_hunter", value: 300 },
        { source: "ufo_believer", target: "cosmic_explorer", value: 200 },
        { source: "conspiracy_buff", target: "ufo_believer", value: 300 },
        { source: "conspiracy_buff", target: "truth_seeker", value: 250 },
        { source: "alien_hunter", target: "ufo_believer", value: 350 },
        { source: "alien_hunter", target: "cosmic_explorer", value: 200 },
        { source: "truth_seeker", target: "conspiracy_buff", value: 300 },
        { source: "truth_seeker", target: "alien_hunter", value: 250 },
        { source: "cosmic_explorer", target: "ufo_believer", value: 200 },
        { source: "cosmic_explorer", target: "alien_hunter", value: 350 },
        
        // Skeptic community internal trust
        { source: "skeptic123", target: "fact_checker", value: 300 },
        { source: "skeptic123", target: "rational_thinker", value: 250 },
        { source: "skeptic123", target: "reality_check", value: 200 },
        { source: "fact_checker", target: "skeptic123", value: 350 },
        { source: "fact_checker", target: "evidence_first", value: 300 },
        { source: "rational_thinker", target: "skeptic123", value: 200 },
        { source: "rational_thinker", target: "fact_checker", value: 250 },
        { source: "evidence_first", target: "fact_checker", value: 350 },
        { source: "evidence_first", target: "rational_thinker", value: 300 },
        { source: "reality_check", target: "skeptic123", value: 200 },
        { source: "reality_check", target: "evidence_first", value: 250 },
        
        // News community internal trust
        { source: "news_junkie", target: "political_analyst", value: 250 },
        { source: "news_junkie", target: "current_events", value: 200 },
        { source: "political_analyst", target: "news_junkie", value: 300 },
        { source: "political_analyst", target: "policy_wonk", value: 250 },
        { source: "policy_wonk", target: "political_analyst", value: 350 },
        { source: "policy_wonk", target: "legal_eagle", value: 200 },
        { source: "current_events", target: "news_junkie", value: 300 },
        { source: "current_events", target: "policy_wonk", value: 150 },
        { source: "legal_eagle", target: "policy_wonk", value: 250 },
        { source: "legal_eagle", target: "political_analyst", value: 200 },
        
        // Cross-community relationships - Tech and Science communities sometimes interact
        { source: "tech_guru", target: "skeptic123", value: 100 },
        { source: "science_fan", target: "evidence_first", value: 150 },
        { source: "rational_thinker", target: "science_fan", value: 100 },
        { source: "fact_checker", target: "tech_guru", value: 50 },
        
        // Skeptics distrust conspiracy theorists
        { source: "skeptic123", target: "ufo_believer", value: -200 },
        { source: "fact_checker", target: "conspiracy_buff", value: -300 },
        { source: "rational_thinker", target: "alien_hunter", value: -250 },
        { source: "evidence_first", target: "truth_seeker", value: -200 },
        { source: "reality_check", target: "cosmic_explorer", value: -150 },
        
        // Some news connections
        { source: "news_junkie", target: "fact_checker", value: 100 },
        { source: "political_analyst", target: "skeptic123", value: 50 },
        { source: "conspiracy_buff", target: "news_junkie", value: -200 }
    ],
    
    // Community information
    communities: [
        { id: 1, name: "Tech & Science", color: "#4285F4" },
        { id: 2, name: "UFO & Conspiracy", color: "#EA4335" },
        { id: 3, name: "Skeptics", color: "#FBBC05" },
        { id: 4, name: "News & Politics", color: "#34A853" }
    ]
};

// Map to quickly look up users by username
const userMap = {};
trustData.users.forEach(user => {
    userMap[user.username] = user;
});

// Function to get user details
function getUserDetails(username) {
    return userMap[username];
}

// Function to get incoming trust relationships for a user
function getIncomingTrust(username) {
    return trustData.relationships.filter(rel => rel.target === username);
}

// Function to get outgoing trust relationships for a user
function getOutgoingTrust(username) {
    return trustData.relationships.filter(rel => rel.source === username);
}

// Function to get community color for a user
function getUserCommunityColor(username) {
    const user = getUserDetails(username);
    if (!user) return "#999999";
    
    const community = trustData.communities.find(c => c.id === user.communityId);
    return community ? community.color : "#999999";
}